### ISSUE TITLE
segmentation fault (core dumped)  hyprpicker

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/hyprpicker#33]
# segmentation fault (core dumped)  hyprpicker error 

![20230509_22h17m22s_grim](https://github.com/hyprwm/hyprpicker/assets/54718375/933cf8d2-b9e4-4e97-829e-edf2aa57abe4)

**Comment by IronRevelation** [comment]
Same thing happens to me

**Comment by n3oney** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f693f0 in wl_cursor_image_get_buffer () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-cursor.so.0
(gdb) bt -full
#0  0x00007ffff7f693f0 in wl_cursor_image_get_buffer () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-cursor.so.0
No symbol table info available.
#1  0x00000000004049f4 in Events::handlePointerEnter (data=<optimized out>, wl_pointer=0x447210, serial=31215, surface=0x4458e0, surface_x=<optimized out>, surface_y=<optimized out>)
    at /nix/store/7df1167jhd0mblch0ylvi452kcjg0dp0-gcc-12.2.0/include/c++/12.2.0/bits/unique_ptr.h:191
        ls = std::unique_ptr<CLayerSurface> = {get() = 0x445720}
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
#2  0x00007ffff7a2f80a in ffi_call_unix64 () from /nix/store/4d4zzb9a4fazq0qv7vvls561l9cxi0zc-libffi-3.4.2/lib/libffi.so.8
No symbol table info available.
#3  0x00007ffff7a2e943 in ffi_call_int () from /nix/store/4d4zzb9a4fazq0qv7vvls561l9cxi0zc-libffi-3.4.2/lib/libffi.so.8
No symbol table info available.
#4  0x00007ffff7f5e741 in wl_closure_invoke () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-client.so.0
No symbol table info available.
#5  0x00007ffff7f5aaaa in dispatch_event.isra () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-client.so.0
No symbol table info available.
#6  0x00007ffff7f5c40c in wl_display_dispatch_queue_pending () from /nix/store/rq2d1gp2hhh4l584112vrkrbijpw7xhm-wayland-1.21.0/lib/libwayland-client.so.0
No symbol table info available.
#7  0x0000000000406da1 in CHyprpicker::init (this=0x43fd60) at /home/neoney/code/hyprpicker/src/hyprpicker.cpp:34
No locals.
#8  0x0000000000403bb6 in main (argc=1, argv=0x7fffffff4028, envp=<optimized out>) at /home/neoney/code/hyprpicker/src/main.cpp:64
No locals.
```

**Comment by n3oney** [comment]
Seems like this is introduced in Hyprland in https://github.com/hyprwm/Hyprland/commit/e7c2ea9724ef11038b14367587d9b4987708b1d1, so best you can do to fix it right now is lock your version to `826dc61e5cfe292a9967bd4397dcff37672fc194`

**Comment by vaxerski** [comment]
fixed with https://github.com/hyprwm/Hyprland/commit/86ef85efaec16a20816d64d4c6aff34c01c0c9b7

**Comment by basilioss** [comment]
Does hyprpicker works without Hyprland? I still have this issue on Gnome 45 (Arch Linux).
```
~ ➜ hyprpicker
zsh: segmentation fault (core dumped)  hyprpicker

~ ➜ gdb /usr/bin/hyprpicker --quiet
Reading symbols from /usr/bin/hyprpicker...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) n
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
(No debugging symbols found in /usr/bin/hyprpicker)
(gdb) run
Starting program: /usr/bin/hyprpicker 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f819d4 in wl_proxy_get_version ()
   from /usr/lib/libwayland-client.so.0
(gdb) 
```
